version: '3'
services:

  drupal:
    user: "${COVID_USER}"
    image:  covid_php
    env_file:
      - .env
    volumes:  [ "${COVID_PROJECT_DIR}:/var/www/html:delegated" ]
    build:
      context: .
      dockerfile: Dockerfile.php
    depends_on:
      - database

  nginx:
    user: "${COVID_USER}"
    image:  covid_nginx
    ports: [ "${COVID_PORT_NGINX}:8080" ]
    volumes:  [ "${COVID_PROJECT_DIR}:/var/www/html:delegated" ]
    build:
      context: .
      dockerfile: Dockerfile.nginx

  database:
    image:  mcr.microsoft.com/mssql/server:5.7.31
    ports: [ "${COVID_PORT_MSSQL}:1433" ]
    environment:
      ACCEPT_EULA: "y"
      SA_PASSWORD: "SuperDrupalSite8"
