  
name: Gatsby

on:
  push:
    paths:
      - "gatsby/*"

defaults:
  run:
    working-directory: ./gatsby

jobs:
  validate:
    name: Validate Gatsby Code Base

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
            
      - run: yarn install

      - run: yarn test
      
      - name: Publish code coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false

      - run: yarn format

      - run: yarn lint

      - run: yarn stylelint
      
      - run: yarn type-check

      - run: yarn build
