  
name: Gatsby

on:
  push:
    paths:
      - "gatsby/*"

defaults:
  run:
    working-directory: ./gatsby

jobs:
  validate:
    name: Validate Gatsby Code Base

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
            
      - run: yarn install

      - run: yarn test
      
      - name: Publish code coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

      - run: yarn format

      - run: yarn lint

      - run: yarn stylelint
      
      - run: yarn type-check

      - run: yarn build
